#!/bin/bash

if [ ! -d ".venv" ]; then
    echo "No .venv directory found. Creating a new python virtual environment..."
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt
else
    source .venv/bin/activate
fi
python3 avignon-edt-webapp.py